version: '3.8'

services:
  api_juegos:
    build: ./API-JUEGOS
    ports:
      - "5000:5000"
    volumes:
      - ./API-JUEGOS:/app
    environment:
      FLASK_ENV: developmen
  api_plantas:
    build: ./API-PLANTAS
    ports:
      - "5001:5000" # Importante: puerto diferente en el host para no chocar
    volumes:
      - ./API-PLANTAS:/app
    environment:
      FLASK_ENV: development
  